CREATE DATABASE emp;
USE emp;
CREATE TABLE employee_data(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
EMP_ID VARCHAR(16) NOT NULL,
EMP_PIN VARCHAR(4),
EMP_LAST VARCHAR(20) NOT NULL,
EMP_FIRST VARCHAR(20) NOT NULL,
EMP_SALARY BOOL NOT NULL,
EMP_WAGE DOUBLE NOT NULL,
EMP_YTD DOUBLE NOT NULL);
CREATE TABLE current_pay_period(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
EMP_ID VARCHAR(16) NOT NULL,
EMP_GROSS DOUBLE NOT NULL,
EMP_WITHHOLDINGS DOUBLE NOT NULL,
EMP_TAXES DOUBLE NOT NULL,
EMP_NET DOUBLE NOT NULL);
CREATE DATABASE users;
USE users;
CREATE TABLE user_data(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(16) NOT NULL,
USER_PASSWORD VARCHAR(24),
USER_SESSION_ID BIGINT NOT NULL
);

